INSERT INTO PUBLIC.PRODUCT(PRODUCTAUTHOR, PRODUCTAUTHORBIO, PRODUCTCATEGORY, PRODUCTCONDITION, PRODUCTDESCRIPTION, PRODUCTNAME, PRODUCTPRICE, PRODUCTPUBLISHER, PRODUCTRELEASEDATE, PRODUCTSTATUS, TOPSELLERSTATUS, UNITINSTOCK, NUMRATING, RATING, TOTALRATING) VALUES
('J. R. R. Tolkien', 'John Ronald Reuel Tolkien, CBE FRSL was an English writer, poet, philologist, and university professor who is best known as the author of the classic high fantasy works The Hobbit, The Lord of the Rings, and The Silmarillion.', 'Fantasy, Adventure', 'new', 'This is a fantasy book', 'The Lord of the Rings', 22.2, 'Allen & Unwin', TIMESTAMP '1954-07-29 00:00:00', 'active', 'active', 6, 0.0, 0.0, 0.0),
('Isaac Asimov', 'Isaac Asimov was an American writer and professor of biochemistry at Boston University. He was known for his works of science fiction and popular science.', 'Science fiction', 'new', 'This is a science fiction', 'I, Robot', 50.0, 'Gnome Press', TIMESTAMP '1950-12-02 00:00:00', 'active', 'inactive', 5, 0.0, 0.0, 0.0),
('Douglas Adams', 'Douglas Noel Adams was an English author, scriptwriter, essayist, humorist, satirist and dramatist. Adams was author of The Hitchhiker''s Guide to the Galaxy, which originated in 1978 as a BBC radio', 'Comic science fiction', 'new', 'This is a comedy science fiction', 'The Ultimate Hitchhiker''s Guide to the Galaxy', 14.0, 'Pan Books', TIMESTAMP '1979-10-12 00:00:00', 'active', 'inactive', 6, 0.0, 0.0, 0.0),
('William Gibson', 'William Ford Gibson is an American-Canadian speculative fiction writer and essayist widely credited with pioneering the science fiction subgenre known as cyberpunk.', 'Science fiction, cyberpunk', 'new', 'this is a science fiction', 'Neuromancer', 18.2, 'Ace', TIMESTAMP '1984-07-01 00:00:00', 'active', 'inactive', 15, 0.0, 0.0, 0.0),
('Scarlett Thomas', 'Scarlett Thomas is an English author and creative writing teacher. She has written nine novels, including The End of Mr. Y and PopCo, and the Worldquake series of children''s books.', 'Novel', 'new', 'This a curse book', 'The End of Mr. Y', 16.0, 'Harcourt Books', TIMESTAMP '2006-04-05 00:00:00', 'active', 'inactive', 14, 0.0, 0.0, 0.0),
('Holly Smale', 'Holly Smale is a British writer. Her first published book, Geek Girl, won the 2014 Waterstones Children''s Book Prize and was shortlisted for the Roald Dahl Funny Prize 2013. Smale is writing a 6-book teen fiction series, also called Geek Girl.', 'Young adult fiction, Fiction', 'new', 'This is a debut novel', 'Geek Girl', 50.0, 'HarperCollins', TIMESTAMP '2013-02-28 00:00:00', 'active', 'active', 40, 0.0, 0.0, 0.0),
('Stephenie Meyer', 'Stephenie Meyer is an American novelist and film producer, best known for her vampire romance series Twilight. The Twilight novels have gained worldwide recognition and sold over 100 million copies, with translations into 37 different languages', 'Young adult, Fantasy, Romance', 'new', 'this is a romance book', 'Eclipse', 15.0, 'Little, Brown', TIMESTAMP '2007-08-07 00:00:00', 'active', 'inactive', 4, 0.0, 0.0, 0.0),
('J.K Rowling', 'Joanne Rowling, CH, OBE, FRSL, FRCPE, writing under the pen names J. K. Rowling and Robert Galbraith, is a British novelist, philanthropist, film and television producer and screenwriter best known for writing the Harry Potter fantasy series.', 'Fantasy, Drama, Young Adult fiction, mystery, Thriller', 'new', 'Thi is a magical book', 'Harry Potter and The Sorcerer''s Stone', 50.0, 'Bloomsbury Publishing (UK), Scholastic (US)', TIMESTAMP '1997-06-26 00:00:00', 'active', 'active', 15, 0.0, 0.0, 0.0),
('Stephenie Meyer', 'Stephenie Meyer is an American novelist and film producer, best known for her vampire romance series Twilight. The Twilight novels have gained worldwide recognition and sold over 100 million copies, with translations into 37 different languages.', 'Young adult, fanatasy, romance, vampire', 'new', 'This is a romance book', 'Twilight', 25.5, 'Little, Brown, and Company', TIMESTAMP '2005-10-05 00:00:00', 'active', 'active', 60, 0.0, 0.0, 0.0),
('C.S. Lewis', 'Clive Staples Lewis was a British novelist, poet, academic, medievalist, literary critic, essayist, lay theologian, broadcaster, lecturer, and Christian apologist. He held academic positions at both Oxford University and Cambridge University.', 'Fantasy Children''s literature', 'new', 'This is a fantasy book', 'Narnia', 15.4, 'HaperCollins', TIMESTAMP '1950-10-16 00:00:00', 'active', 'inactive', 50, 0.0, 0.0, 0.0);
INSERT INTO PUBLIC.PRODUCT( PRODUCTAUTHOR, PRODUCTAUTHORBIO, PRODUCTCATEGORY, PRODUCTCONDITION, PRODUCTDESCRIPTION, PRODUCTNAME, PRODUCTPRICE, PRODUCTPUBLISHER, PRODUCTRELEASEDATE, PRODUCTSTATUS, TOPSELLERSTATUS, UNITINSTOCK, NUMRATING, RATING, TOTALRATING) VALUES
('Stephen King', 'Stephen Edwin King is an American author of horror, supernatural fiction, suspense, science fiction and fantasy', 'Horror, Thriller', 'new', 'This is a scary book', 'IT', 20.0, 'Viking', TIMESTAMP '1986-09-15 00:00:00', 'active', 'inactive', 18, 0.0, 0.0, 0.0),
('Suzanne Collins', 'Suzanne Collins is an American television writer and author, best known as the author of The New York Times best selling series The Underland Chronicles and The Hunger Games trilogy.', 'Dystopian, adventure, science fiction, drama, action', 'new', 'This is a fictional book', 'The Hunger Games', 23.0, 'Scholastic', TIMESTAMP '2008-09-14 00:00:00', 'active', 'active', 40, 0.0, 0.0, 0.0),
('John Green', 'John Michael Green is an American author, vlogger, writer, producer, actor, editor, and educator. He won the 2006 Printz Award for his debut novel, Looking for Alaska, and his sixth novel, The Fault in ...', 'Young adult novel Realistic Fiction, Drama, romance', 'new', 'This is a Romance book', 'The Fault in Our Stars', 20.0, 'Dutton Books', TIMESTAMP '2012-01-10 00:00:00', 'active', 'inactive', 65, 0.0, 0.0, 0.0),
('Veronica Roth', 'Veronica Anne Roth is an American novelist and short story writer, known for her debut New York Times bestselling Divergent trilogy, consisting of Divergent, Insurgent, and Allegiant; and Four: A Divergent Collection.', 'Science fiction, dystopia, young adult fiction', 'new', 'This is an adult fiction', 'Divergent', 25.0, 'Katherine Tegen Books', TIMESTAMP '2011-04-26 00:00:00', 'active', 'active', 45, 0.0, 0.0, 0.0),
('Mary Shelley', 'Mary Wollstonecraft Shelley was an English novelist, short story writer, dramatist, essayist, biographer, and travel writer, best known for her Gothic novel Frankenstein: or, The Modern Prometheus', 'Gothic novel, horror fiction, soft science fiction', 'new', 'this is a horror story', 'Frankenstein', 24.0, 'Lackington, hughes, Harding, Mavor & Jones', TIMESTAMP '1818-01-01 00:00:00', 'active', 'inactive', 50, 0.0, 0.0, 0.0),
('Stephen Hawking', 'Stephen William Hawking CH CBE FRS FRSA was an English theoretical physicist, cosmologist, and author, who was director of research at the Centre for Theoretical Cosmology at the University of Cambridge at the time of his death.', 'Cosmology', 'new', 'This is a study of the universe', 'A Brief History of Time', 75.0, 'Bantam Dell Publishing Group', TIMESTAMP '1988-06-18 00:00:00', 'active', 'inactive', 80, 0.0, 0.0, 0.0),
('Neal Stephenson', 'Neal Town Stephenson is an American writer and game designer known for his works of speculative fiction. His novels have been categorized as science fiction, historical fiction, cyberpunk, postcyberpunk, and baroque.', 'Science fiction, Cyberpunk, Postcyberpunk', 'new', 'This is a science fiction novel', 'Snow Crash', 11.2, 'Bantam Books (USA)', TIMESTAMP '1992-06-24 00:00:00', 'active', 'inactive', 60, 0.0, 0.0, 0.0),
('Ernest Cline', 'Ernest Christy Cline is an American novelist, slam poet, and screenwriter. He is known for his novels Ready Player One and Armada; he also co-wrote the screenplay for the film adaptation of Ready Player One, directed by Steven Spielberg.', 'LitRPG, Science Fiction, Dystopian', 'new', 'This is a futuristic book', 'Ready Player One', 25.0, 'Random House', TIMESTAMP '2011-08-16 00:00:00', 'active', 'active', 40, 0.0, 0.0, 0.0),
('Arthur Golden', 'Arthur Sulzberger Golden is an American writer. He is the author of the bestselling novel Memoirs of a Geisha.', 'Historical novel', 'new', 'This is a life story', 'Memoirs of a Geisha', 22.0, 'Alfred A. Knopf', TIMESTAMP '1997-09-27 00:00:00', 'active', 'inactive', 5, 0.0, 0.0, 0.0),
('Antoine de Saint-Exupery', STRINGDECODE('Antoine Marie Jean-Baptiste Roger, comte de Saint-Exup\u00e9ry was a French writer, poet, aristocrat, journalist, and pioneering aviator. He became a laureate of several of France''s highest literary awards and also won the U.S. National Book Award.'), 'Kid''s literature', 'new', 'This is a kid''s book', 'The Little Prince', 15.0, 'Reynal & Hitchcock', TIMESTAMP '1943-04-20 00:00:00', 'active', 'inactive', 40, 0.0, 0.0, 0.0);
INSERT INTO PUBLIC.PRODUCT(PRODUCTAUTHOR, PRODUCTAUTHORBIO, PRODUCTCATEGORY, PRODUCTCONDITION, PRODUCTDESCRIPTION, PRODUCTNAME, PRODUCTPRICE, PRODUCTPUBLISHER, PRODUCTRELEASEDATE, PRODUCTSTATUS, TOPSELLERSTATUS, UNITINSTOCK, NUMRATING, RATING, TOTALRATING) VALUES
('Steve McConnell', 'Steven C. McConnell is an author of software engineering textbooks such as Code Complete, Rapid Development, and Software Estimation. He is cited as an expert in software engineering and project management.', 'Computer programming', 'new', 'This is A Practical Handbook of Software Construction', 'Code Complete', 100.0, '', TIMESTAMP '1993-08-12 00:00:00', 'active', 'inactive', 70, 0.0, 0.0, 0.0),
('Alan Moore', 'Alan Moore is an English writer known primarily for his work in comic books including Watchmen, V for Vendetta, The Ballad of Halo Jones and From Hell.', 'Comic, Superheroes, Futuristic', 'new', 'This is a comic', 'Watchmen', 15.2, 'DC Comics', TIMESTAMP '1986-09-15 00:00:00', 'active', 'inactive', 8, 1.0, 2.0, 2.0);
