DROP TABLE IF EXISTS PRODUCT;

CREATE TABLE PUBLIC.PRODUCT(
    ID INTEGER NOT NULL PRIMARY KEY AUTO_INCREMENT,
    PRODUCTAUTHOR VARCHAR(255),
    PRODUCTAUTHORBIO VARCHAR(255),
    PRODUCTCATEGORY VARCHAR(255),
    PRODUCTCONDITION VARCHAR(255),
    PRODUCTDESCRIPTION VARCHAR(255),
    PRODUCTNAME VARCHAR(255),
    PRODUCTPRICE DOUBLE NOT NULL,
    PRODUCTPUBLISHER VARCHAR(255),
    PRODUCTRELEASEDATE DATETIME,
    PRODUCTSTATUS VARCHAR(255),
    TOPSELLERSTATUS VARCHAR(255),
    UNITINSTOCK INTEGER NOT NULL,
    NUMRATING DOUBLE,
    RATING DOUBLE,
    TOTALRATING DOUBLE
);